{% set name = "nabs" %}
{% set version = "1.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/nabs/archive/v{{ version }}.tar.gz
  sha256: 86e4ac26349196119e9b359c6dc7bfc40a86fd452f41de7d5c888af249ae0176

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.9
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.9
    - bluesky-base <1.11,>=1.6.5
    - numpy
    - ophyd
    - pandas
    - scipy
    - toolz
  run_constrained:
    - pyqt =5

test:
  imports:
    - nabs

about:
  dev_url: https://github.com/pcdshub/nabs
  home: https://github.com/pcdshub/nabs
  summary: 'NABS: Not a beamline scientist. Beamline automatation that should be handled by code, not by people.'
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - conda-forge/pdcsdevices
