{% set name = "nabs" %}
{% set version = "1.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/nabs/archive/v{{ version }}.tar.gz
  sha256: 0503a33c27d81854eeb267d1af86a99e2784ae9931a1a35cc848b9889e4a5d9d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - bluesky-base >=1.6.5
    - numpy
    - ophyd
    - pandas
    - scipy
    - toolz
  run_constrained:
    - pyqt =5

test:
  requires:
    - python {{ python_min }}
  imports:
    - nabs

about:
  dev_url: https://github.com/pcdshub/nabs
  home: https://github.com/pcdshub/nabs
  summary: 'NABS: Not a beamline scientist. Beamline automatation that should be handled by code, not by people.'
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - conda-forge/pcdsdevices
